// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: fileservice.proto

#include "fileservice.pb.h"
#include "fileservice.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace fileengine {

static const char* FileService_method_names[] = {
  "/fileengine.FileService/MakeDirectory",
  "/fileengine.FileService/RemoveDirectory",
  "/fileengine.FileService/ListDirectory",
  "/fileengine.FileService/CreateFile",
  "/fileengine.FileService/DeleteFile",
  "/fileengine.FileService/UndeleteFile",
  "/fileengine.FileService/WriteFile",
  "/fileengine.FileService/ReadFile",
  "/fileengine.FileService/GetFileInfo",
  "/fileengine.FileService/FileExists",
  "/fileengine.FileService/MoveFile",
  "/fileengine.FileService/CopyFile",
  "/fileengine.FileService/RenameFile",
  "/fileengine.FileService/ListVersions",
  "/fileengine.FileService/ReadVersion",
  "/fileengine.FileService/SetMetadata",
  "/fileengine.FileService/GetMetadata",
  "/fileengine.FileService/GetAllMetadata",
  "/fileengine.FileService/DeleteMetadata",
  "/fileengine.FileService/GetMetadataForVersion",
  "/fileengine.FileService/GetAllMetadataForVersion",
  "/fileengine.FileService/WriteFileStream",
  "/fileengine.FileService/ReadFileStream",
  "/fileengine.FileService/ResolvePath",
  "/fileengine.FileService/EvaluateACL",
};

std::unique_ptr< FileService::Stub> FileService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FileService::Stub> stub(new FileService::Stub(channel, options));
  return stub;
}

FileService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_MakeDirectory_(FileService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RemoveDirectory_(FileService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListDirectory_(FileService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateFile_(FileService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteFile_(FileService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UndeleteFile_(FileService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WriteFile_(FileService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReadFile_(FileService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetFileInfo_(FileService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FileExists_(FileService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_MoveFile_(FileService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CopyFile_(FileService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RenameFile_(FileService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListVersions_(FileService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReadVersion_(FileService_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetMetadata_(FileService_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetMetadata_(FileService_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAllMetadata_(FileService_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteMetadata_(FileService_method_names[18], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetMetadataForVersion_(FileService_method_names[19], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAllMetadataForVersion_(FileService_method_names[20], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WriteFileStream_(FileService_method_names[21], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_ReadFileStream_(FileService_method_names[22], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ResolvePath_(FileService_method_names[23], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_EvaluateACL_(FileService_method_names[24], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FileService::Stub::MakeDirectory(::grpc::ClientContext* context, const ::fileengine::MakeDirectoryRequest& request, ::fileengine::MakeDirectoryResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::MakeDirectoryRequest, ::fileengine::MakeDirectoryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MakeDirectory_, context, request, response);
}

void FileService::Stub::async::MakeDirectory(::grpc::ClientContext* context, const ::fileengine::MakeDirectoryRequest* request, ::fileengine::MakeDirectoryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::MakeDirectoryRequest, ::fileengine::MakeDirectoryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MakeDirectory_, context, request, response, std::move(f));
}

void FileService::Stub::async::MakeDirectory(::grpc::ClientContext* context, const ::fileengine::MakeDirectoryRequest* request, ::fileengine::MakeDirectoryResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MakeDirectory_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::MakeDirectoryResponse>* FileService::Stub::PrepareAsyncMakeDirectoryRaw(::grpc::ClientContext* context, const ::fileengine::MakeDirectoryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::MakeDirectoryResponse, ::fileengine::MakeDirectoryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MakeDirectory_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::MakeDirectoryResponse>* FileService::Stub::AsyncMakeDirectoryRaw(::grpc::ClientContext* context, const ::fileengine::MakeDirectoryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMakeDirectoryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::RemoveDirectory(::grpc::ClientContext* context, const ::fileengine::RemoveDirectoryRequest& request, ::fileengine::RemoveDirectoryResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::RemoveDirectoryRequest, ::fileengine::RemoveDirectoryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RemoveDirectory_, context, request, response);
}

void FileService::Stub::async::RemoveDirectory(::grpc::ClientContext* context, const ::fileengine::RemoveDirectoryRequest* request, ::fileengine::RemoveDirectoryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::RemoveDirectoryRequest, ::fileengine::RemoveDirectoryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RemoveDirectory_, context, request, response, std::move(f));
}

void FileService::Stub::async::RemoveDirectory(::grpc::ClientContext* context, const ::fileengine::RemoveDirectoryRequest* request, ::fileengine::RemoveDirectoryResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RemoveDirectory_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::RemoveDirectoryResponse>* FileService::Stub::PrepareAsyncRemoveDirectoryRaw(::grpc::ClientContext* context, const ::fileengine::RemoveDirectoryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::RemoveDirectoryResponse, ::fileengine::RemoveDirectoryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RemoveDirectory_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::RemoveDirectoryResponse>* FileService::Stub::AsyncRemoveDirectoryRaw(::grpc::ClientContext* context, const ::fileengine::RemoveDirectoryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRemoveDirectoryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::ListDirectory(::grpc::ClientContext* context, const ::fileengine::ListDirectoryRequest& request, ::fileengine::ListDirectoryResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::ListDirectoryRequest, ::fileengine::ListDirectoryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListDirectory_, context, request, response);
}

void FileService::Stub::async::ListDirectory(::grpc::ClientContext* context, const ::fileengine::ListDirectoryRequest* request, ::fileengine::ListDirectoryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::ListDirectoryRequest, ::fileengine::ListDirectoryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListDirectory_, context, request, response, std::move(f));
}

void FileService::Stub::async::ListDirectory(::grpc::ClientContext* context, const ::fileengine::ListDirectoryRequest* request, ::fileengine::ListDirectoryResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListDirectory_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::ListDirectoryResponse>* FileService::Stub::PrepareAsyncListDirectoryRaw(::grpc::ClientContext* context, const ::fileengine::ListDirectoryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::ListDirectoryResponse, ::fileengine::ListDirectoryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListDirectory_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::ListDirectoryResponse>* FileService::Stub::AsyncListDirectoryRaw(::grpc::ClientContext* context, const ::fileengine::ListDirectoryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListDirectoryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::CreateFile(::grpc::ClientContext* context, const ::fileengine::CreateFileRequest& request, ::fileengine::CreateFileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::CreateFileRequest, ::fileengine::CreateFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateFile_, context, request, response);
}

void FileService::Stub::async::CreateFile(::grpc::ClientContext* context, const ::fileengine::CreateFileRequest* request, ::fileengine::CreateFileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::CreateFileRequest, ::fileengine::CreateFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateFile_, context, request, response, std::move(f));
}

void FileService::Stub::async::CreateFile(::grpc::ClientContext* context, const ::fileengine::CreateFileRequest* request, ::fileengine::CreateFileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::CreateFileResponse>* FileService::Stub::PrepareAsyncCreateFileRaw(::grpc::ClientContext* context, const ::fileengine::CreateFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::CreateFileResponse, ::fileengine::CreateFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::CreateFileResponse>* FileService::Stub::AsyncCreateFileRaw(::grpc::ClientContext* context, const ::fileengine::CreateFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::DeleteFile(::grpc::ClientContext* context, const ::fileengine::DeleteFileRequest& request, ::fileengine::DeleteFileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::DeleteFileRequest, ::fileengine::DeleteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteFile_, context, request, response);
}

void FileService::Stub::async::DeleteFile(::grpc::ClientContext* context, const ::fileengine::DeleteFileRequest* request, ::fileengine::DeleteFileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::DeleteFileRequest, ::fileengine::DeleteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteFile_, context, request, response, std::move(f));
}

void FileService::Stub::async::DeleteFile(::grpc::ClientContext* context, const ::fileengine::DeleteFileRequest* request, ::fileengine::DeleteFileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::DeleteFileResponse>* FileService::Stub::PrepareAsyncDeleteFileRaw(::grpc::ClientContext* context, const ::fileengine::DeleteFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::DeleteFileResponse, ::fileengine::DeleteFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::DeleteFileResponse>* FileService::Stub::AsyncDeleteFileRaw(::grpc::ClientContext* context, const ::fileengine::DeleteFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::UndeleteFile(::grpc::ClientContext* context, const ::fileengine::UndeleteFileRequest& request, ::fileengine::UndeleteFileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::UndeleteFileRequest, ::fileengine::UndeleteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UndeleteFile_, context, request, response);
}

void FileService::Stub::async::UndeleteFile(::grpc::ClientContext* context, const ::fileengine::UndeleteFileRequest* request, ::fileengine::UndeleteFileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::UndeleteFileRequest, ::fileengine::UndeleteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UndeleteFile_, context, request, response, std::move(f));
}

void FileService::Stub::async::UndeleteFile(::grpc::ClientContext* context, const ::fileengine::UndeleteFileRequest* request, ::fileengine::UndeleteFileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UndeleteFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::UndeleteFileResponse>* FileService::Stub::PrepareAsyncUndeleteFileRaw(::grpc::ClientContext* context, const ::fileengine::UndeleteFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::UndeleteFileResponse, ::fileengine::UndeleteFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UndeleteFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::UndeleteFileResponse>* FileService::Stub::AsyncUndeleteFileRaw(::grpc::ClientContext* context, const ::fileengine::UndeleteFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUndeleteFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::WriteFile(::grpc::ClientContext* context, const ::fileengine::WriteFileRequest& request, ::fileengine::WriteFileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::WriteFileRequest, ::fileengine::WriteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_WriteFile_, context, request, response);
}

void FileService::Stub::async::WriteFile(::grpc::ClientContext* context, const ::fileengine::WriteFileRequest* request, ::fileengine::WriteFileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::WriteFileRequest, ::fileengine::WriteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteFile_, context, request, response, std::move(f));
}

void FileService::Stub::async::WriteFile(::grpc::ClientContext* context, const ::fileengine::WriteFileRequest* request, ::fileengine::WriteFileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WriteFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::WriteFileResponse>* FileService::Stub::PrepareAsyncWriteFileRaw(::grpc::ClientContext* context, const ::fileengine::WriteFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::WriteFileResponse, ::fileengine::WriteFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_WriteFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::WriteFileResponse>* FileService::Stub::AsyncWriteFileRaw(::grpc::ClientContext* context, const ::fileengine::WriteFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWriteFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::ReadFile(::grpc::ClientContext* context, const ::fileengine::ReadFileRequest& request, ::fileengine::ReadFileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::ReadFileRequest, ::fileengine::ReadFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadFile_, context, request, response);
}

void FileService::Stub::async::ReadFile(::grpc::ClientContext* context, const ::fileengine::ReadFileRequest* request, ::fileengine::ReadFileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::ReadFileRequest, ::fileengine::ReadFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadFile_, context, request, response, std::move(f));
}

void FileService::Stub::async::ReadFile(::grpc::ClientContext* context, const ::fileengine::ReadFileRequest* request, ::fileengine::ReadFileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::ReadFileResponse>* FileService::Stub::PrepareAsyncReadFileRaw(::grpc::ClientContext* context, const ::fileengine::ReadFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::ReadFileResponse, ::fileengine::ReadFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::ReadFileResponse>* FileService::Stub::AsyncReadFileRaw(::grpc::ClientContext* context, const ::fileengine::ReadFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::GetFileInfo(::grpc::ClientContext* context, const ::fileengine::GetFileInfoRequest& request, ::fileengine::GetFileInfoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::GetFileInfoRequest, ::fileengine::GetFileInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetFileInfo_, context, request, response);
}

void FileService::Stub::async::GetFileInfo(::grpc::ClientContext* context, const ::fileengine::GetFileInfoRequest* request, ::fileengine::GetFileInfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::GetFileInfoRequest, ::fileengine::GetFileInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFileInfo_, context, request, response, std::move(f));
}

void FileService::Stub::async::GetFileInfo(::grpc::ClientContext* context, const ::fileengine::GetFileInfoRequest* request, ::fileengine::GetFileInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFileInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::GetFileInfoResponse>* FileService::Stub::PrepareAsyncGetFileInfoRaw(::grpc::ClientContext* context, const ::fileengine::GetFileInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::GetFileInfoResponse, ::fileengine::GetFileInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetFileInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::GetFileInfoResponse>* FileService::Stub::AsyncGetFileInfoRaw(::grpc::ClientContext* context, const ::fileengine::GetFileInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetFileInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::FileExists(::grpc::ClientContext* context, const ::fileengine::FileExistsRequest& request, ::fileengine::FileExistsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::FileExistsRequest, ::fileengine::FileExistsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FileExists_, context, request, response);
}

void FileService::Stub::async::FileExists(::grpc::ClientContext* context, const ::fileengine::FileExistsRequest* request, ::fileengine::FileExistsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::FileExistsRequest, ::fileengine::FileExistsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FileExists_, context, request, response, std::move(f));
}

void FileService::Stub::async::FileExists(::grpc::ClientContext* context, const ::fileengine::FileExistsRequest* request, ::fileengine::FileExistsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FileExists_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::FileExistsResponse>* FileService::Stub::PrepareAsyncFileExistsRaw(::grpc::ClientContext* context, const ::fileengine::FileExistsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::FileExistsResponse, ::fileengine::FileExistsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FileExists_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::FileExistsResponse>* FileService::Stub::AsyncFileExistsRaw(::grpc::ClientContext* context, const ::fileengine::FileExistsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFileExistsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::MoveFile(::grpc::ClientContext* context, const ::fileengine::MoveFileRequest& request, ::fileengine::MoveFileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::MoveFileRequest, ::fileengine::MoveFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MoveFile_, context, request, response);
}

void FileService::Stub::async::MoveFile(::grpc::ClientContext* context, const ::fileengine::MoveFileRequest* request, ::fileengine::MoveFileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::MoveFileRequest, ::fileengine::MoveFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MoveFile_, context, request, response, std::move(f));
}

void FileService::Stub::async::MoveFile(::grpc::ClientContext* context, const ::fileengine::MoveFileRequest* request, ::fileengine::MoveFileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MoveFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::MoveFileResponse>* FileService::Stub::PrepareAsyncMoveFileRaw(::grpc::ClientContext* context, const ::fileengine::MoveFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::MoveFileResponse, ::fileengine::MoveFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MoveFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::MoveFileResponse>* FileService::Stub::AsyncMoveFileRaw(::grpc::ClientContext* context, const ::fileengine::MoveFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMoveFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::CopyFile(::grpc::ClientContext* context, const ::fileengine::CopyFileRequest& request, ::fileengine::CopyFileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::CopyFileRequest, ::fileengine::CopyFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CopyFile_, context, request, response);
}

void FileService::Stub::async::CopyFile(::grpc::ClientContext* context, const ::fileengine::CopyFileRequest* request, ::fileengine::CopyFileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::CopyFileRequest, ::fileengine::CopyFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CopyFile_, context, request, response, std::move(f));
}

void FileService::Stub::async::CopyFile(::grpc::ClientContext* context, const ::fileengine::CopyFileRequest* request, ::fileengine::CopyFileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CopyFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::CopyFileResponse>* FileService::Stub::PrepareAsyncCopyFileRaw(::grpc::ClientContext* context, const ::fileengine::CopyFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::CopyFileResponse, ::fileengine::CopyFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CopyFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::CopyFileResponse>* FileService::Stub::AsyncCopyFileRaw(::grpc::ClientContext* context, const ::fileengine::CopyFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCopyFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::RenameFile(::grpc::ClientContext* context, const ::fileengine::RenameFileRequest& request, ::fileengine::RenameFileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::RenameFileRequest, ::fileengine::RenameFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RenameFile_, context, request, response);
}

void FileService::Stub::async::RenameFile(::grpc::ClientContext* context, const ::fileengine::RenameFileRequest* request, ::fileengine::RenameFileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::RenameFileRequest, ::fileengine::RenameFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RenameFile_, context, request, response, std::move(f));
}

void FileService::Stub::async::RenameFile(::grpc::ClientContext* context, const ::fileengine::RenameFileRequest* request, ::fileengine::RenameFileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RenameFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::RenameFileResponse>* FileService::Stub::PrepareAsyncRenameFileRaw(::grpc::ClientContext* context, const ::fileengine::RenameFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::RenameFileResponse, ::fileengine::RenameFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RenameFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::RenameFileResponse>* FileService::Stub::AsyncRenameFileRaw(::grpc::ClientContext* context, const ::fileengine::RenameFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRenameFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::ListVersions(::grpc::ClientContext* context, const ::fileengine::ListVersionsRequest& request, ::fileengine::ListVersionsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::ListVersionsRequest, ::fileengine::ListVersionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListVersions_, context, request, response);
}

void FileService::Stub::async::ListVersions(::grpc::ClientContext* context, const ::fileengine::ListVersionsRequest* request, ::fileengine::ListVersionsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::ListVersionsRequest, ::fileengine::ListVersionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListVersions_, context, request, response, std::move(f));
}

void FileService::Stub::async::ListVersions(::grpc::ClientContext* context, const ::fileengine::ListVersionsRequest* request, ::fileengine::ListVersionsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListVersions_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::ListVersionsResponse>* FileService::Stub::PrepareAsyncListVersionsRaw(::grpc::ClientContext* context, const ::fileengine::ListVersionsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::ListVersionsResponse, ::fileengine::ListVersionsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListVersions_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::ListVersionsResponse>* FileService::Stub::AsyncListVersionsRaw(::grpc::ClientContext* context, const ::fileengine::ListVersionsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListVersionsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::ReadVersion(::grpc::ClientContext* context, const ::fileengine::ReadVersionRequest& request, ::fileengine::ReadVersionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::ReadVersionRequest, ::fileengine::ReadVersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadVersion_, context, request, response);
}

void FileService::Stub::async::ReadVersion(::grpc::ClientContext* context, const ::fileengine::ReadVersionRequest* request, ::fileengine::ReadVersionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::ReadVersionRequest, ::fileengine::ReadVersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadVersion_, context, request, response, std::move(f));
}

void FileService::Stub::async::ReadVersion(::grpc::ClientContext* context, const ::fileengine::ReadVersionRequest* request, ::fileengine::ReadVersionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadVersion_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::ReadVersionResponse>* FileService::Stub::PrepareAsyncReadVersionRaw(::grpc::ClientContext* context, const ::fileengine::ReadVersionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::ReadVersionResponse, ::fileengine::ReadVersionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadVersion_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::ReadVersionResponse>* FileService::Stub::AsyncReadVersionRaw(::grpc::ClientContext* context, const ::fileengine::ReadVersionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadVersionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::SetMetadata(::grpc::ClientContext* context, const ::fileengine::SetMetadataRequest& request, ::fileengine::SetMetadataResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::SetMetadataRequest, ::fileengine::SetMetadataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetMetadata_, context, request, response);
}

void FileService::Stub::async::SetMetadata(::grpc::ClientContext* context, const ::fileengine::SetMetadataRequest* request, ::fileengine::SetMetadataResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::SetMetadataRequest, ::fileengine::SetMetadataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetMetadata_, context, request, response, std::move(f));
}

void FileService::Stub::async::SetMetadata(::grpc::ClientContext* context, const ::fileengine::SetMetadataRequest* request, ::fileengine::SetMetadataResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetMetadata_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::SetMetadataResponse>* FileService::Stub::PrepareAsyncSetMetadataRaw(::grpc::ClientContext* context, const ::fileengine::SetMetadataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::SetMetadataResponse, ::fileengine::SetMetadataRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetMetadata_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::SetMetadataResponse>* FileService::Stub::AsyncSetMetadataRaw(::grpc::ClientContext* context, const ::fileengine::SetMetadataRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetMetadataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::GetMetadata(::grpc::ClientContext* context, const ::fileengine::GetMetadataRequest& request, ::fileengine::GetMetadataResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::GetMetadataRequest, ::fileengine::GetMetadataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMetadata_, context, request, response);
}

void FileService::Stub::async::GetMetadata(::grpc::ClientContext* context, const ::fileengine::GetMetadataRequest* request, ::fileengine::GetMetadataResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::GetMetadataRequest, ::fileengine::GetMetadataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMetadata_, context, request, response, std::move(f));
}

void FileService::Stub::async::GetMetadata(::grpc::ClientContext* context, const ::fileengine::GetMetadataRequest* request, ::fileengine::GetMetadataResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMetadata_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::GetMetadataResponse>* FileService::Stub::PrepareAsyncGetMetadataRaw(::grpc::ClientContext* context, const ::fileengine::GetMetadataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::GetMetadataResponse, ::fileengine::GetMetadataRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMetadata_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::GetMetadataResponse>* FileService::Stub::AsyncGetMetadataRaw(::grpc::ClientContext* context, const ::fileengine::GetMetadataRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMetadataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::GetAllMetadata(::grpc::ClientContext* context, const ::fileengine::GetAllMetadataRequest& request, ::fileengine::GetAllMetadataResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::GetAllMetadataRequest, ::fileengine::GetAllMetadataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAllMetadata_, context, request, response);
}

void FileService::Stub::async::GetAllMetadata(::grpc::ClientContext* context, const ::fileengine::GetAllMetadataRequest* request, ::fileengine::GetAllMetadataResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::GetAllMetadataRequest, ::fileengine::GetAllMetadataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllMetadata_, context, request, response, std::move(f));
}

void FileService::Stub::async::GetAllMetadata(::grpc::ClientContext* context, const ::fileengine::GetAllMetadataRequest* request, ::fileengine::GetAllMetadataResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllMetadata_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::GetAllMetadataResponse>* FileService::Stub::PrepareAsyncGetAllMetadataRaw(::grpc::ClientContext* context, const ::fileengine::GetAllMetadataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::GetAllMetadataResponse, ::fileengine::GetAllMetadataRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAllMetadata_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::GetAllMetadataResponse>* FileService::Stub::AsyncGetAllMetadataRaw(::grpc::ClientContext* context, const ::fileengine::GetAllMetadataRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAllMetadataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::DeleteMetadata(::grpc::ClientContext* context, const ::fileengine::DeleteMetadataRequest& request, ::fileengine::DeleteMetadataResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::DeleteMetadataRequest, ::fileengine::DeleteMetadataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteMetadata_, context, request, response);
}

void FileService::Stub::async::DeleteMetadata(::grpc::ClientContext* context, const ::fileengine::DeleteMetadataRequest* request, ::fileengine::DeleteMetadataResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::DeleteMetadataRequest, ::fileengine::DeleteMetadataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteMetadata_, context, request, response, std::move(f));
}

void FileService::Stub::async::DeleteMetadata(::grpc::ClientContext* context, const ::fileengine::DeleteMetadataRequest* request, ::fileengine::DeleteMetadataResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteMetadata_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::DeleteMetadataResponse>* FileService::Stub::PrepareAsyncDeleteMetadataRaw(::grpc::ClientContext* context, const ::fileengine::DeleteMetadataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::DeleteMetadataResponse, ::fileengine::DeleteMetadataRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteMetadata_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::DeleteMetadataResponse>* FileService::Stub::AsyncDeleteMetadataRaw(::grpc::ClientContext* context, const ::fileengine::DeleteMetadataRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteMetadataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::GetMetadataForVersion(::grpc::ClientContext* context, const ::fileengine::GetMetadataForVersionRequest& request, ::fileengine::GetMetadataForVersionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::GetMetadataForVersionRequest, ::fileengine::GetMetadataForVersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMetadataForVersion_, context, request, response);
}

void FileService::Stub::async::GetMetadataForVersion(::grpc::ClientContext* context, const ::fileengine::GetMetadataForVersionRequest* request, ::fileengine::GetMetadataForVersionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::GetMetadataForVersionRequest, ::fileengine::GetMetadataForVersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMetadataForVersion_, context, request, response, std::move(f));
}

void FileService::Stub::async::GetMetadataForVersion(::grpc::ClientContext* context, const ::fileengine::GetMetadataForVersionRequest* request, ::fileengine::GetMetadataForVersionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMetadataForVersion_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::GetMetadataForVersionResponse>* FileService::Stub::PrepareAsyncGetMetadataForVersionRaw(::grpc::ClientContext* context, const ::fileengine::GetMetadataForVersionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::GetMetadataForVersionResponse, ::fileengine::GetMetadataForVersionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMetadataForVersion_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::GetMetadataForVersionResponse>* FileService::Stub::AsyncGetMetadataForVersionRaw(::grpc::ClientContext* context, const ::fileengine::GetMetadataForVersionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMetadataForVersionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::GetAllMetadataForVersion(::grpc::ClientContext* context, const ::fileengine::GetAllMetadataForVersionRequest& request, ::fileengine::GetAllMetadataForVersionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::GetAllMetadataForVersionRequest, ::fileengine::GetAllMetadataForVersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAllMetadataForVersion_, context, request, response);
}

void FileService::Stub::async::GetAllMetadataForVersion(::grpc::ClientContext* context, const ::fileengine::GetAllMetadataForVersionRequest* request, ::fileengine::GetAllMetadataForVersionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::GetAllMetadataForVersionRequest, ::fileengine::GetAllMetadataForVersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllMetadataForVersion_, context, request, response, std::move(f));
}

void FileService::Stub::async::GetAllMetadataForVersion(::grpc::ClientContext* context, const ::fileengine::GetAllMetadataForVersionRequest* request, ::fileengine::GetAllMetadataForVersionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAllMetadataForVersion_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::GetAllMetadataForVersionResponse>* FileService::Stub::PrepareAsyncGetAllMetadataForVersionRaw(::grpc::ClientContext* context, const ::fileengine::GetAllMetadataForVersionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::GetAllMetadataForVersionResponse, ::fileengine::GetAllMetadataForVersionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAllMetadataForVersion_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::GetAllMetadataForVersionResponse>* FileService::Stub::AsyncGetAllMetadataForVersionRaw(::grpc::ClientContext* context, const ::fileengine::GetAllMetadataForVersionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAllMetadataForVersionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientWriter< ::fileengine::WriteFileStreamRequest>* FileService::Stub::WriteFileStreamRaw(::grpc::ClientContext* context, ::fileengine::WriteFileStreamResponse* response) {
  return ::grpc::internal::ClientWriterFactory< ::fileengine::WriteFileStreamRequest>::Create(channel_.get(), rpcmethod_WriteFileStream_, context, response);
}

void FileService::Stub::async::WriteFileStream(::grpc::ClientContext* context, ::fileengine::WriteFileStreamResponse* response, ::grpc::ClientWriteReactor< ::fileengine::WriteFileStreamRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::fileengine::WriteFileStreamRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_WriteFileStream_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::fileengine::WriteFileStreamRequest>* FileService::Stub::AsyncWriteFileStreamRaw(::grpc::ClientContext* context, ::fileengine::WriteFileStreamResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::fileengine::WriteFileStreamRequest>::Create(channel_.get(), cq, rpcmethod_WriteFileStream_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::fileengine::WriteFileStreamRequest>* FileService::Stub::PrepareAsyncWriteFileStreamRaw(::grpc::ClientContext* context, ::fileengine::WriteFileStreamResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::fileengine::WriteFileStreamRequest>::Create(channel_.get(), cq, rpcmethod_WriteFileStream_, context, response, false, nullptr);
}

::grpc::ClientReader< ::fileengine::ReadFileStreamResponse>* FileService::Stub::ReadFileStreamRaw(::grpc::ClientContext* context, const ::fileengine::ReadFileStreamRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::fileengine::ReadFileStreamResponse>::Create(channel_.get(), rpcmethod_ReadFileStream_, context, request);
}

void FileService::Stub::async::ReadFileStream(::grpc::ClientContext* context, const ::fileengine::ReadFileStreamRequest* request, ::grpc::ClientReadReactor< ::fileengine::ReadFileStreamResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::fileengine::ReadFileStreamResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_ReadFileStream_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::fileengine::ReadFileStreamResponse>* FileService::Stub::AsyncReadFileStreamRaw(::grpc::ClientContext* context, const ::fileengine::ReadFileStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::fileengine::ReadFileStreamResponse>::Create(channel_.get(), cq, rpcmethod_ReadFileStream_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::fileengine::ReadFileStreamResponse>* FileService::Stub::PrepareAsyncReadFileStreamRaw(::grpc::ClientContext* context, const ::fileengine::ReadFileStreamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::fileengine::ReadFileStreamResponse>::Create(channel_.get(), cq, rpcmethod_ReadFileStream_, context, request, false, nullptr);
}

::grpc::Status FileService::Stub::ResolvePath(::grpc::ClientContext* context, const ::fileengine::ResolvePathRequest& request, ::fileengine::ResolvePathResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::ResolvePathRequest, ::fileengine::ResolvePathResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ResolvePath_, context, request, response);
}

void FileService::Stub::async::ResolvePath(::grpc::ClientContext* context, const ::fileengine::ResolvePathRequest* request, ::fileengine::ResolvePathResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::ResolvePathRequest, ::fileengine::ResolvePathResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ResolvePath_, context, request, response, std::move(f));
}

void FileService::Stub::async::ResolvePath(::grpc::ClientContext* context, const ::fileengine::ResolvePathRequest* request, ::fileengine::ResolvePathResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ResolvePath_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::ResolvePathResponse>* FileService::Stub::PrepareAsyncResolvePathRaw(::grpc::ClientContext* context, const ::fileengine::ResolvePathRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::ResolvePathResponse, ::fileengine::ResolvePathRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ResolvePath_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::ResolvePathResponse>* FileService::Stub::AsyncResolvePathRaw(::grpc::ClientContext* context, const ::fileengine::ResolvePathRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncResolvePathRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FileService::Stub::EvaluateACL(::grpc::ClientContext* context, const ::fileengine::EvaluateACLRequest& request, ::fileengine::EvaluateACLResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fileengine::EvaluateACLRequest, ::fileengine::EvaluateACLResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_EvaluateACL_, context, request, response);
}

void FileService::Stub::async::EvaluateACL(::grpc::ClientContext* context, const ::fileengine::EvaluateACLRequest* request, ::fileengine::EvaluateACLResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fileengine::EvaluateACLRequest, ::fileengine::EvaluateACLResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EvaluateACL_, context, request, response, std::move(f));
}

void FileService::Stub::async::EvaluateACL(::grpc::ClientContext* context, const ::fileengine::EvaluateACLRequest* request, ::fileengine::EvaluateACLResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EvaluateACL_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fileengine::EvaluateACLResponse>* FileService::Stub::PrepareAsyncEvaluateACLRaw(::grpc::ClientContext* context, const ::fileengine::EvaluateACLRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fileengine::EvaluateACLResponse, ::fileengine::EvaluateACLRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_EvaluateACL_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fileengine::EvaluateACLResponse>* FileService::Stub::AsyncEvaluateACLRaw(::grpc::ClientContext* context, const ::fileengine::EvaluateACLRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEvaluateACLRaw(context, request, cq);
  result->StartCall();
  return result;
}

FileService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::MakeDirectoryRequest, ::fileengine::MakeDirectoryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::MakeDirectoryRequest* req,
             ::fileengine::MakeDirectoryResponse* resp) {
               return service->MakeDirectory(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::RemoveDirectoryRequest, ::fileengine::RemoveDirectoryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::RemoveDirectoryRequest* req,
             ::fileengine::RemoveDirectoryResponse* resp) {
               return service->RemoveDirectory(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::ListDirectoryRequest, ::fileengine::ListDirectoryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::ListDirectoryRequest* req,
             ::fileengine::ListDirectoryResponse* resp) {
               return service->ListDirectory(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::CreateFileRequest, ::fileengine::CreateFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::CreateFileRequest* req,
             ::fileengine::CreateFileResponse* resp) {
               return service->CreateFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::DeleteFileRequest, ::fileengine::DeleteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::DeleteFileRequest* req,
             ::fileengine::DeleteFileResponse* resp) {
               return service->DeleteFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::UndeleteFileRequest, ::fileengine::UndeleteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::UndeleteFileRequest* req,
             ::fileengine::UndeleteFileResponse* resp) {
               return service->UndeleteFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::WriteFileRequest, ::fileengine::WriteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::WriteFileRequest* req,
             ::fileengine::WriteFileResponse* resp) {
               return service->WriteFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::ReadFileRequest, ::fileengine::ReadFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::ReadFileRequest* req,
             ::fileengine::ReadFileResponse* resp) {
               return service->ReadFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::GetFileInfoRequest, ::fileengine::GetFileInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::GetFileInfoRequest* req,
             ::fileengine::GetFileInfoResponse* resp) {
               return service->GetFileInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::FileExistsRequest, ::fileengine::FileExistsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::FileExistsRequest* req,
             ::fileengine::FileExistsResponse* resp) {
               return service->FileExists(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::MoveFileRequest, ::fileengine::MoveFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::MoveFileRequest* req,
             ::fileengine::MoveFileResponse* resp) {
               return service->MoveFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::CopyFileRequest, ::fileengine::CopyFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::CopyFileRequest* req,
             ::fileengine::CopyFileResponse* resp) {
               return service->CopyFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::RenameFileRequest, ::fileengine::RenameFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::RenameFileRequest* req,
             ::fileengine::RenameFileResponse* resp) {
               return service->RenameFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::ListVersionsRequest, ::fileengine::ListVersionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::ListVersionsRequest* req,
             ::fileengine::ListVersionsResponse* resp) {
               return service->ListVersions(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::ReadVersionRequest, ::fileengine::ReadVersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::ReadVersionRequest* req,
             ::fileengine::ReadVersionResponse* resp) {
               return service->ReadVersion(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::SetMetadataRequest, ::fileengine::SetMetadataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::SetMetadataRequest* req,
             ::fileengine::SetMetadataResponse* resp) {
               return service->SetMetadata(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::GetMetadataRequest, ::fileengine::GetMetadataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::GetMetadataRequest* req,
             ::fileengine::GetMetadataResponse* resp) {
               return service->GetMetadata(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::GetAllMetadataRequest, ::fileengine::GetAllMetadataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::GetAllMetadataRequest* req,
             ::fileengine::GetAllMetadataResponse* resp) {
               return service->GetAllMetadata(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::DeleteMetadataRequest, ::fileengine::DeleteMetadataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::DeleteMetadataRequest* req,
             ::fileengine::DeleteMetadataResponse* resp) {
               return service->DeleteMetadata(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[19],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::GetMetadataForVersionRequest, ::fileengine::GetMetadataForVersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::GetMetadataForVersionRequest* req,
             ::fileengine::GetMetadataForVersionResponse* resp) {
               return service->GetMetadataForVersion(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[20],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::GetAllMetadataForVersionRequest, ::fileengine::GetAllMetadataForVersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::GetAllMetadataForVersionRequest* req,
             ::fileengine::GetAllMetadataForVersionResponse* resp) {
               return service->GetAllMetadataForVersion(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[21],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< FileService::Service, ::fileengine::WriteFileStreamRequest, ::fileengine::WriteFileStreamResponse>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::fileengine::WriteFileStreamRequest>* reader,
             ::fileengine::WriteFileStreamResponse* resp) {
               return service->WriteFileStream(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[22],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< FileService::Service, ::fileengine::ReadFileStreamRequest, ::fileengine::ReadFileStreamResponse>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::ReadFileStreamRequest* req,
             ::grpc::ServerWriter<::fileengine::ReadFileStreamResponse>* writer) {
               return service->ReadFileStream(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[23],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::ResolvePathRequest, ::fileengine::ResolvePathResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::ResolvePathRequest* req,
             ::fileengine::ResolvePathResponse* resp) {
               return service->ResolvePath(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileService_method_names[24],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileService::Service, ::fileengine::EvaluateACLRequest, ::fileengine::EvaluateACLResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fileengine::EvaluateACLRequest* req,
             ::fileengine::EvaluateACLResponse* resp) {
               return service->EvaluateACL(ctx, req, resp);
             }, this)));
}

FileService::Service::~Service() {
}

::grpc::Status FileService::Service::MakeDirectory(::grpc::ServerContext* context, const ::fileengine::MakeDirectoryRequest* request, ::fileengine::MakeDirectoryResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::RemoveDirectory(::grpc::ServerContext* context, const ::fileengine::RemoveDirectoryRequest* request, ::fileengine::RemoveDirectoryResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::ListDirectory(::grpc::ServerContext* context, const ::fileengine::ListDirectoryRequest* request, ::fileengine::ListDirectoryResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::CreateFile(::grpc::ServerContext* context, const ::fileengine::CreateFileRequest* request, ::fileengine::CreateFileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::DeleteFile(::grpc::ServerContext* context, const ::fileengine::DeleteFileRequest* request, ::fileengine::DeleteFileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::UndeleteFile(::grpc::ServerContext* context, const ::fileengine::UndeleteFileRequest* request, ::fileengine::UndeleteFileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::WriteFile(::grpc::ServerContext* context, const ::fileengine::WriteFileRequest* request, ::fileengine::WriteFileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::ReadFile(::grpc::ServerContext* context, const ::fileengine::ReadFileRequest* request, ::fileengine::ReadFileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::GetFileInfo(::grpc::ServerContext* context, const ::fileengine::GetFileInfoRequest* request, ::fileengine::GetFileInfoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::FileExists(::grpc::ServerContext* context, const ::fileengine::FileExistsRequest* request, ::fileengine::FileExistsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::MoveFile(::grpc::ServerContext* context, const ::fileengine::MoveFileRequest* request, ::fileengine::MoveFileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::CopyFile(::grpc::ServerContext* context, const ::fileengine::CopyFileRequest* request, ::fileengine::CopyFileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::RenameFile(::grpc::ServerContext* context, const ::fileengine::RenameFileRequest* request, ::fileengine::RenameFileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::ListVersions(::grpc::ServerContext* context, const ::fileengine::ListVersionsRequest* request, ::fileengine::ListVersionsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::ReadVersion(::grpc::ServerContext* context, const ::fileengine::ReadVersionRequest* request, ::fileengine::ReadVersionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::SetMetadata(::grpc::ServerContext* context, const ::fileengine::SetMetadataRequest* request, ::fileengine::SetMetadataResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::GetMetadata(::grpc::ServerContext* context, const ::fileengine::GetMetadataRequest* request, ::fileengine::GetMetadataResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::GetAllMetadata(::grpc::ServerContext* context, const ::fileengine::GetAllMetadataRequest* request, ::fileengine::GetAllMetadataResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::DeleteMetadata(::grpc::ServerContext* context, const ::fileengine::DeleteMetadataRequest* request, ::fileengine::DeleteMetadataResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::GetMetadataForVersion(::grpc::ServerContext* context, const ::fileengine::GetMetadataForVersionRequest* request, ::fileengine::GetMetadataForVersionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::GetAllMetadataForVersion(::grpc::ServerContext* context, const ::fileengine::GetAllMetadataForVersionRequest* request, ::fileengine::GetAllMetadataForVersionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::WriteFileStream(::grpc::ServerContext* context, ::grpc::ServerReader< ::fileengine::WriteFileStreamRequest>* reader, ::fileengine::WriteFileStreamResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::ReadFileStream(::grpc::ServerContext* context, const ::fileengine::ReadFileStreamRequest* request, ::grpc::ServerWriter< ::fileengine::ReadFileStreamResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::ResolvePath(::grpc::ServerContext* context, const ::fileengine::ResolvePathRequest* request, ::fileengine::ResolvePathResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileService::Service::EvaluateACL(::grpc::ServerContext* context, const ::fileengine::EvaluateACLRequest* request, ::fileengine::EvaluateACLResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace fileengine

